# Generated by Django 4.2.30 on 2026-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(default='table_tennis', max_length=20, verbose_name='运动类型')),
                ('date', models.DateField(verbose_name='日期')),
                ('time_start', models.TimeField(verbose_name='开始时间')),
                ('time_end', models.TimeField(verbose_name='结束时间')),
                ('district', models.CharField(max_length=50, verbose_name='所在区')),
                ('notes', models.TextField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('max_players', models.IntegerField(default=4, verbose_name='最大参与人数')),
                ('skill_level_required', models.IntegerField(blank=True, choices=[(1, '初学者'), (2, '初级'), (3, '中级'), (4, '高级'), (5, '专业级')], null=True, verbose_name='水平要求')),
                ('status', models.CharField(choices=[('open', '开放报名'), ('full', '已满员'), ('cancelled', '已取消'), ('completed', '已完成')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
                'ordering': ['-date', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='MatchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'ordering': ['created_at'],
            },
        ),
    ]
