# Generated by Django 4.2.30 on 2026-05-05 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_applications', to=settings.AUTH_USER_MODEL, verbose_name='报名人'),
        ),
        migrations.AddField(
            model_name='matchapplication',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='matches.match', verbose_name='赛事'),
        ),
        migrations.AddField(
            model_name='match',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterUniqueTogether(
            name='matchapplication',
            unique_together={('match', 'applicant')},
        ),
    ]
