# Generated by Django 4.2.30 on 2026-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='球馆名称')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('district', models.CharField(max_length=50, verbose_name='所在区')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '球馆',
                'verbose_name_plural': '球馆',
                'ordering': ['name'],
            },
        ),
    ]
