# Generated by Django 4.2.30 on 2026-05-05 09:09

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('wechat_openid', models.CharField(max_length=100, unique=True, verbose_name='微信 openid')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('skill_level', models.IntegerField(blank=True, choices=[(1, '初学者'), (2, '初级'), (3, '中级'), (4, '高级'), (5, '专业级')], null=True, verbose_name='水平等级')),
                ('district', models.CharField(default='', max_length=50, verbose_name='所在区')),
                ('paddle_type', models.CharField(blank=True, choices=[('横板', '横板'), ('直板', '直板'), ('日直', '日直'), ('异形', '异形')], max_length=10, null=True, verbose_name='球板类型')),
                ('rubber_type', models.CharField(blank=True, choices=[('反胶', '反胶'), ('正胶', '正胶'), ('长胶', '长胶'), ('生胶', '生胶')], max_length=10, null=True, verbose_name='胶皮类型')),
                ('bio', models.CharField(blank=True, default='', max_length=50, verbose_name='自我介绍')),
                ('avatar', models.URLField(blank=True, default='', verbose_name='头像 URL')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='资料是否完善')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
